# Generated by Django 2.2.2 on 2020-01-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwdata',
            name='alias',
        ),
        migrations.DeleteModel(
            name='Post_Return',
        ),
        migrations.DeleteModel(
            name='Rcv_server_data',
        ),
        migrations.DeleteModel(
            name='Set_param',
        ),
        migrations.DeleteModel(
            name='Set_Time',
        ),
        migrations.DeleteModel(
            name='TimeStatus',
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GWData',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Sensor_data',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
