"""
Django settings for GatewaySite project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')n0vse!y)9)npl9z0h_td%9%hs6+u=1tl#3r=0sc4cubq8*ly-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gateway.apps.GatewayConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GatewaySite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GatewaySite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db1haoGW.sqlite3'),
        'NAME': os.path.join(BASE_DIR, 'ORISONIC_GW_db.sqlite3'),
        # 'NAME': os.path.join(BASE_DIR, 'dbtest.sqlite3'),
    }
}


# Password validation

# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
AUTH_USER_MODEL = 'gateway.UserProfile'

STATIC_URL = '/static/'
# STATIC_ROOT = 'static'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

LOGIN_URL = '/login/'

# 初始化时间
initial_time = {'days': 30, 'hours': 0, 'minutes': 0}

heart_timeout = {'minutes': 1, 'seconds': 30}

headers_dict = {
    'gwntid': 'gwntid',
    'get_data_manually': 'get_data_manually',
    'gwdata': 'gwdata',
    'add_sensor': 'add_sensor',
    'update_sensor': 'update_sensor',
    'remove_sensor': 'remove_sensor',
    'sync_sensors': 'sync_sensors',
    'server_status': 'server_status',
    'heart_ping': 'heart_ping',
    'resume_sensor': 'resume_sensor',
    'pause_sensor': 'pause_sensor',
    'update_gateway': 'update_gateway',
    'check_time_between_gws': 'check_time_between_gws',

}


# EMQ X SETTINGS
MQTT_USERNAME = "ORISONIC"
MQTT_PASSWORD = "ORISONIC2020"
MQTT_HOST = "121.36.220.210"
# MQTT_HOST = "47.93.190.54"
# crtPath = BASE_DIR + r"/crt_192.168.0.44"
crtPath = BASE_DIR + r"/crt_47.93.190.54"
ca_certs = "%s/ca/MyRootCA.pem" % crtPath
certfile = "%s/client/MyClient1.pem" % crtPath
keyfile = "%s/client/MyClient1.key" % crtPath

# SM2


# 错误日志
ERROR_LOG_FILE = os.path.join(BASE_DIR, "log", 'error.log')
# 运行日志
RUN_LOG_FILE = os.path.join(BASE_DIR, "log", 'run.log')

